version: '3'

services:
  grant-api:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./:/app
      - /home/node/node_modules
  mongo:
    image: mongo
    ports:
      - 27017:27017
